<div id="footer">
		<div class="body">
			<div class="wrapper clearfix">
				<div id="links">
					<div>
						<h4>Links</h4>
						<ul>
							<li>
								<a href="facebook.com" target="_blank">Facebook Group</a>
							</li>
							<li>
								<a href="wiki.spacesim.org">The Wiki</a>
							</li>							
							<li>
								<a href="legal.php" target="_blank">Legal</a>
							</li>							
						</ul>
					</div>
				</div>
				<p class="footnote">
					Copyright OCESS 2014
				</p>
			</div>
		</div>
	</div>
</body>
</html>
