<!doctype html>
<html>
  <head>
  	<meta charset="UTF-8">
	<title>OCE Space Simulation</title>
	<link rel="shortcut icon" href="favicon.ico" />
	<link rel="stylesheet" href="css/style.css" type="text/css">
  		<div id="header">
			<div class="wrapper clearfix">
				 <div id="logo">
				 	  <a href="index.php"><img src="images/logo.gif" alt="LOGO"></a>
				 </div>
				 <ul id="navigation">
				 	 <li class="selected">
					 	 <a href="index.php">Home</a>
				     </li>
				     <li>
					 	 <a href="about.php">About</a>
				     </li>
					 <li>
					 	 <a href="blog.php">Blog</a>
					 </li>
					 <li>
					 	 <a href="contact.php">Contact Us</a>
					 </li>
					 <li>
					 	 <a href="eeps.php">EEPS</a>
					 </li>
					 <li>
					 	 <a href="downloads.php">Downloads</a>
					 </li>
				 </ul>
			</div>
	</div>
  </head>
